config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: 'blog/posts#index'
  
  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end
  
  scope module: 'blog' do 
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
  
  resources :releases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
  
  validates_presence_of :name, on: :update
  
  def change_password(attrs)
    update(password: attrs[:new_password], password_confirmation: attrs[:new_password_confirmation])
  end
  
  def display_name
    if name.present?
      name
    else
      "Author"
    end
  end
  
end

app/controllers/author/posts_controller.rb
module Author
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to author_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to author_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to author_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url)
      end
  end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
  class AccountsController < AuthorController
    
    def edit
    end
    
    def update_info
      if current_author.update(author_info_params)
        flash[:success] = 'Successfully saved info'
      else
        flash[:danger] = current_author.display_error_messages
      end
      redirect_to authors_account_path
    end
    
    def change_password
      author = current_author
      if author.valid_password?(author_password_params[:current_password])
        if author.change_password(author_password_params)
          sign_in(author, bypass: true)
          flash[:success] = 'Successfully changed password.'
        else
          flash[:danger] = author.display_error_messages
        end
      else
        flash[:danger] = 'Current password was incorrect.'
      end
      redirect_to authors_account_path
    end
    
    private
    
    def author_info_params
      params.require(:author).permit(:name, :email, :bio)
    end
    
    def author_password_params
      params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
    end
    
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.most_recent.new
    end

    # GET /posts/1/edit
    def edit
    end
    
    def publish
      @post.publish
      redirect_to authors_posts_url
    end
    
    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.most_recent.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.most_recent.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
      end
  end
end

app/views/authors/accounts/edit.html.erb
<div class="row">
	<!-- Basic info section -->	
	<%= form_tag authors_info_path, method: :put do %>
		<%= fields_for :author do |f| %>
		<div class="col-md-6">
			<div class="card">
				<div class="card-block">
					<div class="card-title">
						Basic info
					</div>
				</div>

				<ul class="list-group list-group-flush">
					<li class="list-group-item">
					    <div class="field">
					      <%= f.label :name %>
					      <%= f.text_field :name, value: current_author.name, class: 'form-control' %>
					    </div>
					</li>
					<li class="list-group-item">
					    <div class="field">
					      <%= f.label :email %>
					      <%= f.text_field :email, value: current_author.email, class: 'form-control' %>
					    </div>
					</li>
					<li class="list-group-item">
					    <div class="field">
					      <%= f.label :bio %>
					      <%= f.text_area :bio, value: current_author.bio, class: 'form-control' %>
					    </div>
					</li>
					<li class="list-group-item">
						<%= f.submit "Update info", class: 'btn btn-primary' %>
					</li>
				</ul>
			</div>
		</div>
		<% end%>
	<% end %>
	
	<!-- Change password section -->
	<%= form_tag authors_change_password_path, method: :put do %>
		<%= fields_for :author do |f| %>
			<div class="col-md-6">
				<div class="card">
					<div class="card-block">
						<div class="card-title">
							Password
						</div>
					</div>

					<ul class="list-group list-group-flush">
						<li class="list-group-item">
						    <div class="field">
						      <%= f.label :current_password %>
						      <%= f.password_field :current_password, class: 'form-control' %>
						    </div>
						</li>
						<li class="list-group-item">
						    <div class="field">
						      <%= f.label :new_password %>
						      <%= f.password_field :new_password, class: 'form-control' %>
						    </div>
						</li>
						<li class="list-group-item">
						    <div class="field">
						      <%= f.label :new_password_confirmation %>
						      <%= f.password_field :new_password_confirmation, class: 'form-control' %>
						    </div>
						</li>
						<li class="list-group-item">
							<%= f.submit "Change password", class: 'btn btn-warning' %>
						</li>
					</ul>
				</div>
			</div>
		<% end %>
	<% end %>
</div>