config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: 'blog/posts#index'
  
  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end
  
  scope module: 'blog' do 
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
  
  resources :releases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
  
  validates_presence_of :name, on: :update
  
  def change_password(attrs)
    update(password: attrs[:new_password], password_confirmation: attrs[:new_password_confirmation])
  end
  
  def display_name
    if name.present?
      name
    else
      "Author"
    end
  end
  
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#  published        :boolean          default(FALSE)
#  published_at     :datetime
#

class Post < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  belongs_to :author
  
  PER_PAGE = 2
  
  scope :most_recent, -> { order(published_at: :desc) }
  scope :published, -> { where(published: :true) }
  scope :recent_paginated, -> (page) { most_recent.paginate(page: page, per_page: PER_PAGE) }
  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }
  
  scope :list_for, -> (page, tag) do
    recent_paginated(page).with_tag(tag)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    if published_at.present?
      "Published #{published_at.strftime('%-b %-d, %Y')}"
    else
      "Not published yet"
    end
  end
  
  def publish
    update(published: true, published_at: Time.now)
  end
  
  def unpublish
    update(published: false, published_at: nil)
  end
  
end

app/controllers/author/posts_controller.rb
module Author
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to author_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to author_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to author_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url)
      end
  end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
  class AccountsController < AuthorController
    
    def edit
    end
    
    def update_info
      if current_author.update(author_info_params)
        flash[:success] = 'Successfully saved info'
      else
        flash[:danger] = current_author.display_error_messages
      end
      redirect_to authors_account_path
    end
    
    def change_password
      author = current_author
      if author.valid_password?(author_password_params[:current_password])
        if author.change_password(author_password_params)
          sign_in(author, bypass: true)
          flash[:success] = 'Successfully changed password.'
        else
          flash[:danger] = author.display_error_messages
        end
      else
        flash[:danger] = 'Current password was incorrect.'
      end
      redirect_to authors_account_path
    end
    
    private
    
    def author_info_params
      params.require(:author).permit(:name, :email, :bio)
    end
    
    def author_password_params
      params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
    end
    
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.most_recent.new
    end

    # GET /posts/1/edit
    def edit
    end
    
    def publish
      @post.publish
      redirect_to authors_posts_url
    end
    
    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.most_recent.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.most_recent.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
      end
  end
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController

    # GET /posts
    # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
    end
    
    private
    
    def storage
      Post.published
    end

  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url)do |form| %>
	<% if post.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

		  <ul>
		  <% post.errors.full_messages.each do |message| %>
		    <li><%= message %></li>
		  <% end %>
		  </ul>
		</div>
	<% end %>

	<div class="row">
		<div class="col-md-3">
			<div class="card" style="width: 20rem;">
			  <div class="card-block">
				<% if @post.new_record? %>
			    	<h4 class="card-title">New post</h4>
				<% else %>
					<h4 class="card-title">
						<b>Edit</b>
						<span class="thin-text"><%= @post.title %></span>
					</h4>
				<% end %>
			  </div>
			  <ul class="list-group list-group-flush">
			    <li class="list-group-item">
				    <div class="field">
				      <%= form.label :title %>
				      <%= form.text_field :title, class: 'form-control' %>
				    </div>
			    </li>
			    <li class="list-group-item">
				    <div class="field">
				      <%= form.label :banner_image_url %>
				      <%= form.text_field :banner_image_url, class: 'form-control' %>
				    </div>
			    </li>
			    <li class="list-group-item">
				    <div class="field">
				      <%= form.label :description %>
				      <%= form.text_area :description, class: 'form-control' %>
				    </div>
			    </li>
			    <li class="list-group-item">
				    <div class="field">
				      <%= form.label 'Tags' %>
				      <%= form.text_area :tag_list, class: 'form-control' %>
				    </div>
			    </li>
			    <li class="list-group-item">
					<div class="actions">
						<%= form.submit "Save blog post", class: 'btn btn-success btn-lg btn-block' %>
					</div>
			    </li>
			  </ul>
			</div>
			<% if @post.persisted? %>
				<%= link_to 'Show', @post %> |
			<% end %>
			<%= link_to 'Back', authors_posts_path %>
		</div>
		
		<div class="col-md-1">
		</div>
	
		<div class="col-md-8">
		    <div class="field">
			  <%= form.text_area :body, :class => "tinymce" %>
		    </div>
		</div>
	</div>


<% end %>

app/views/authors/posts/_post.html.erb
<tr>
	<td><%= link_to post.title, authors_post_path(post) %></td>
	<td></td>
	<% if post.published? %>
		<td><%= link_to 'Unpublish', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %></td>
	<% else %>
		<td><%= link_to 'Publish', publish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-success' %></td>
	<% end %>
	<td><%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %></td>
	<td><%= link_to 'Remove', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:author, 'active') %>

<div class="row">
	<div>
		<%= link_to 'New post', new_authors_post_path, class: 'btn btn-primary btn-lg'%>
	</div>
	<table class="table table-striped">
		<tr>
			<th colspan="5">Title</th>
		</tr>
		<%= render @posts %>
	</table>
</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author, 'active') %>

<%= render 'form', post: @post, url: authors_posts_url %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div>
	<%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
	<%= link_to 'Remove', authors_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
</div>

<div class="row">
	<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
		<h1><%= @post.title %></h1>
		<p><%= @post.display_day_published%></p>
		<%= @post.body.html_safe %>
	</div>
</div>