config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: 'blog/posts#index'
  
  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end
  
  scope module: 'blog' do 
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
  
  resources :releases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/releases_controller.rb
class ReleasesController < BlogController
  before_action :set_release, only: [:show, :edit, :update, :destroy]

  # GET /releases
  # GET /releases.json
  def index
    @releases = Release.all
  end

  # GET /releases/1
  # GET /releases/1.json
  def show
  end

  # GET /releases/new
  def new
    @release = Release.new
  end

  # GET /releases/1/edit
  def edit
  end

  # POST /releases
  # POST /releases.json
  def create
    @release = Release.new(release_params)

    respond_to do |format|
      if @release.save
        format.html { redirect_to @release, notice: 'Release was successfully created.' }
        format.json { render :show, status: :created, location: @release }
      else
        format.html { render :new }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /releases/1
  # PATCH/PUT /releases/1.json
  def update
    respond_to do |format|
      if @release.update(release_params)
        format.html { redirect_to @release, notice: 'Release was successfully updated.' }
        format.json { render :show, status: :ok, location: @release }
      else
        format.html { render :edit }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /releases/1
  # DELETE /releases/1.json
  def destroy
    @release.destroy
    respond_to do |format|
      format.html { redirect_to releases_url, notice: 'Release was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_release
      @release = Release.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def release_params
      params.require(:release).permit(:number, :release_date, :name, :description, :style, :abv, :case_vol, :can_limit, :price, :additional, :canning_date, :canning_phrase, :label_inspiration, :instagram_url)
    end
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/views/releases/_form.html.erb
<%= form_with(model: release, local: true) do |form| %>
  <% if release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(release.errors.count, "error") %> prohibited this release from being saved:</h2>

      <ul>
      <% release.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :release_number %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.datetime_select :release_date, id: :release_release_date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :release_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :release_description %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style, id: :release_style %>
  </div>

  <div class="field">
    <%= form.label :abv %>
    <%= form.text_field :abv, id: :release_abv %>
  </div>

  <div class="field">
    <%= form.label :case_vol %>
    <%= form.number_field :case_vol, id: :release_case_vol %>
  </div>

  <div class="field">
    <%= form.label :can_limit %>
    <%= form.number_field :can_limit, id: :release_can_limit %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :release_price %>
  </div>

  <div class="field">
    <%= form.label :additional %>
    <%= form.text_area :additional, id: :release_additional %>
  </div>

  <div class="field">
    <%= form.label :canning_date %>
    <%= form.datetime_select :canning_date, id: :release_canning_date %>
  </div>

  <div class="field">
    <%= form.label :canning_phrase %>
    <%= form.text_field :canning_phrase, id: :release_canning_phrase %>
  </div>

  <div class="field">
    <%= form.label :label_inspiration %>
    <%= form.text_area :label_inspiration, id: :release_label_inspiration %>
  </div>

  <div class="field">
    <%= form.label :instagram_url %>
    <%= form.text_field :instagram_url, id: :release_instagram_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/releases/edit.html.erb
<h1>Editing Release</h1>

<%= render 'form', release: @release %>

<%= link_to 'Show', @release %> |
<%= link_to 'Back', releases_path %>

app/views/releases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Releases</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Release date</th>
      <th>Name</th>
      <th>Description</th>
      <th>Style</th>
      <th>Abv</th>
      <th>Case vol</th>
      <th>Can limit</th>
      <th>Price</th>
      <th>Additional</th>
      <th>Canning date</th>
      <th>Canning phrase</th>
      <th>Label inspiration</th>
      <th>Instagram url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @releases.each do |release| %>
      <tr>
        <td><%= release.number %></td>
        <td><%= release.release_date %></td>
        <td><%= release.name %></td>
        <td><%= release.description %></td>
        <td><%= release.style %></td>
        <td><%= release.abv %></td>
        <td><%= release.case_vol %></td>
        <td><%= release.can_limit %></td>
        <td><%= release.price %></td>
        <td><%= release.additional %></td>
        <td><%= release.canning_date %></td>
        <td><%= release.canning_phrase %></td>
        <td><%= release.label_inspiration %></td>
        <td><%= release.instagram_url %></td>
        <td><%= link_to 'Show', release %></td>
        <td><%= link_to 'Edit', edit_release_path(release) %></td>
        <td><%= link_to 'Destroy', release, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Release', new_release_path %>

app/views/releases/new.html.erb
<h1>New Release</h1>

<%= render 'form', release: @release %>

<%= link_to 'Back', releases_path %>

app/views/releases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @release.number %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @release.release_date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @release.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @release.description %>
</p>

<p>
  <strong>Style:</strong>
  <%= @release.style %>
</p>

<p>
  <strong>Abv:</strong>
  <%= @release.abv %>
</p>

<p>
  <strong>Case vol:</strong>
  <%= @release.case_vol %>
</p>

<p>
  <strong>Can limit:</strong>
  <%= @release.can_limit %>
</p>

<p>
  <strong>Price:</strong>
  <%= @release.price %>
</p>

<p>
  <strong>Additional:</strong>
  <%= @release.additional %>
</p>

<p>
  <strong>Canning date:</strong>
  <%= @release.canning_date %>
</p>

<p>
  <strong>Canning phrase:</strong>
  <%= @release.canning_phrase %>
</p>

<p>
  <strong>Label inspiration:</strong>
  <%= @release.label_inspiration %>
</p>

<p>
  <blockquote class="instagram-media" data-instgrm-permalink="<%= @release.instagram_url %>" data-instgrm-version="8" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);">
	  <div style="padding:8px;"> 
		  <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:37.5% 0; text-align:center; width:100%;"> 
			  <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;">
			  	
			  </div>
		  </div>
	  </div>
  </blockquote>
  <script async defer src="//www.instagram.com/embed.js"></script>
</p>

<%= link_to 'Edit', edit_release_path(@release) %> |
<%= link_to 'Back', releases_path %>