config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: 'blog/posts#index'
  
  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end
  
  scope module: 'blog' do 
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
  
  resources :releases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
  <div class="collapse-bg p-a-1">
    <div class='card'>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
		<% if author_signed_in? %>
	        <li class="list-group-item">
	          <%= link_to 'My posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
	        </li>
  	        <li class="list-group-item">
  	          <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "nav-link" %>
  	      	</li>
		<% end %>
      </ul>
    </div>
  </div>
</div>

<nav class="navbar navbar-light bg-faded">
  <div class='container'>
    <a class='navbar-brand' href='/'>
      Frog<span class='light'>blog</span>
    </a>
    <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <ul class="nav navbar-nav pull-sm-right hidden-xs-down">
      <li class="nav-item">
        <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
      </li>
	  <% if author_signed_in? %>
		  <li class="nav-item dropdown author-nav">
	          <a class="nav-link dropdown-toggle <%= yield(:author) %>" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	            <%= current_author.display_name %>
	          </a>
	          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	          	<%= link_to 'My posts', authors_posts_path, class: "dropdown-item" %>
				<%= link_to 'Account', authors_account_path, class: "dropdown-item" %>
	           	<%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "dropdown-item" %>
	          </div>
		  </li>
	  <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | DS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <%= render 'layouts/navbar' %>
	  <div class="container <%= controller_name %> <%= action_name %>">
		  <%= yield %>
	  </div>
  </body>
</html>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | DS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=fs9pqlyzmux7vdwww5iwh6co2vyiwts684qaomk4a9mkkgsr"></script>
  </head>

  <body>
	  <%= render 'layouts/navbar' %>
	  <div class="container <%= controller_name %> <%= action_name %>">
		  <% if flash.any? %>
		  	<% flash.keys.each do |key| %>
		  		<div class="alert alert-<%= key.to_s %>" alert-dismissible fade show role="alert">
		  			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		  				<span aria-hidden="true">&times;</span>
		  			</button>
		  			<%= flash[key] %>
		  		</div>
		  	<% end %>
		  <% end %>
		  
		  <%= yield %>
	  </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | DS</title>
    <%= csrf_meta_tags %>
	<link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700|Montserrat:300,400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <%= render 'layouts/navbar' %>
	  <div class="container <%= controller_name %> <%= action_name %>">
		  <%= yield %>
	  </div>
  </body>
</html>